language: cpp

os: linux-ppc64le

sudo: required

services: docker

env:
    matrix:
    - RUN_ON_CONTAINER=fedora-rawhide
    - RUN_ON_CONTAINER=ubuntu-20.04

install:
    - docker build --pull -t ${RUN_ON_CONTAINER} -f lsvpd-ci/Dockerfile-${RUN_ON_CONTAINER} .

script:
    - >
      docker run
      --security-opt seccomp=unconfined
      --volume $HOME/.ccache:/root/.ccache
      --volume `pwd`:/build
      --tmpfs /tmp/
      --rm -t $RUN_ON_CONTAINER
      bash -c "./lsvpd-ci/build-${RUN_ON_CONTAINER}.sh";
